spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/mydb
    username: sa
    password:
    console:
      enabled: true
      path: /console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
